[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dj_telegram_bot"
version = "0.1.7"
description = "The fastest way to build a production-ready Telegram bot on Django"
authors = [
  { name = "zankoAN", email = "zankoAn4@gmail.com" }
]
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }
requires-python = ">=3.12"
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 6.0",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "build>=1.6.1",
    "django>=6.0",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "twine>=6.2.0",
]

[project.optional-dependencies]
dev = [
    "django-stubs>=6.0",
]

[dependency-groups]
dev = [
    "twine>=6.2.0",
]

[project.urls]
Homepage = "https://github.com/zankoAn/dj_telegram_bot"
Repository = "https://github.com/zankoAn/dj_telegram_bot"

[tool.hatch.build.targets.wheel]
packages = ["dj_telegram_bot"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 60

[tool.hatch.build.targets.sdist]
exclude = [
  ".venv",
  ".git",
  "__pycache__",
  ".pytest_cache",
  "build",
  "dist",
  "assets",
]