# Generated by Django 6.0.7 on 2026-07-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_update', models.BooleanField(default=False)),
                ('update_msg', models.TextField(default='bot is updated !')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('link', models.CharField(max_length=70, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard_type', models.CharField(choices=[('REPLY', 'Reply Keyboard Markup'), ('INLINE', 'Inline Keyboard Markup')], default='REPLY', max_length=10)),
                ('resize_keyboard', models.BooleanField(default=True)),
                ('one_time_keyboard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('related_step', models.CharField(default='home', max_length=80, verbose_name='related step')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('row', models.PositiveIntegerField(default=0)),
                ('column', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_buttons', to='contrib.keyboard')),
            ],
        ),
        migrations.AddField(
            model_name='keyboard',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='contrib.message'),
        ),
    ]
